name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LaTeX and FreeSerif font
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-xetex texlive-latex-extra xindy fonts-freefont-otf

      - name: Update TeX packages
        run: |
          #sudo tlmgr update --all
          echo disabled

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.15"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync

      - name: Build HTML
        run: |
          source .venv/bin/activate
          make html SPHINXOPTS="-W"

      - name: Build PDF
        run: |
          source .venv/bin/activate
          make pdf SPHINXOPTS="-W"
